//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mercado.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceString {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceString() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mercado.Resources.ResourceString", typeof(ResourceString).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abreviatura.
        /// </summary>
        internal static string ABREVIATURA {
            get {
                return ResourceManager.GetString("ABREVIATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atenção.
        /// </summary>
        internal static string ATENCAO {
            get {
                return ResourceManager.GetString("ATENCAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mercado.mdb.
        /// </summary>
        internal static string BANCO {
            get {
                return ResourceManager.GetString("BANCO", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Cadastros {
            get {
                object obj = ResourceManager.GetObject("Cadastros", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Código.
        /// </summary>
        internal static string CODIGO {
            get {
                return ResourceManager.GetString("CODIGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DATA {
            get {
                return ResourceManager.GetString("DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        internal static string DESCRICAO {
            get {
                return ResourceManager.GetString("DESCRICAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error do Banco de Dados.
        /// </summary>
        internal static string ERROR_BANCO {
            get {
                return ResourceManager.GetString("ERROR_BANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string GRUPO {
            get {
                return ResourceManager.GetString("GRUPO", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Movimentacao {
            get {
                object obj = ResourceManager.GetObject("Movimentacao", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja abandonar as alterações na tela sem salvar.
        /// </summary>
        internal static string PERGUNTA_ALTERCAO_CAMPOS {
            get {
                return ResourceManager.GetString("PERGUNTA_ALTERCAO_CAMPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja atualizar o item {0}.
        /// </summary>
        internal static string QUESTION_ATUALIZAR {
            get {
                return ResourceManager.GetString("QUESTION_ATUALIZAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja excluir o item {0}.
        /// </summary>
        internal static string QUESTION_EXCLUIR {
            get {
                return ResourceManager.GetString("QUESTION_EXCLUIR", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Relatorios {
            get {
                object obj = ResourceManager.GetObject("Relatorios", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and100572.
        /// </summary>
        internal static string SENHA {
            get {
                return ResourceManager.GetString("SENHA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        internal static string USUARIO {
            get {
                return ResourceManager.GetString("USUARIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo breviatura esté em vázio.
        /// </summary>
        internal static string VALIDA_ABREVIATURA {
            get {
                return ResourceManager.GetString("VALIDA_ABREVIATURA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione um grupo.
        /// </summary>
        internal static string VALIDA_COMBO_GRUPOS {
            get {
                return ResourceManager.GetString("VALIDA_COMBO_GRUPOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campo descrição está vázio.
        /// </summary>
        internal static string VALIDA_DESCRICAO {
            get {
                return ResourceManager.GetString("VALIDA_DESCRICAO", resourceCulture);
            }
        }
    }
}
